# Configuration for DDPM++ from Score-SDE.
model:
  # The number of noise scales
  num_scales: 1000
  # The number of features/channels at the start of
  # the network.
  num_features: 128
  # Resnet block channel multipliers.
  channel_multipliers: [1, 2, 2, 2]
  # The number of resnet blocks per resolution.
  num_resnet_blocks: 2
  # The resolution to apply attention layers.
  attention_resolutions: [16, 8]
  # The number of attention heads to use
  num_attention_heads_downsample: 4
  num_attention_heads_upsample: 4
  # Use scale/shift of the GroupNorm in the timestep embedding.
  # This is called Adaptive Group Normalization in the paper.
  use_scale_shift_norm: True
  # Perform resampling using convolutions.
  resamp_with_conv: True
  # BigGAN style resnet block to perform up/down sampling.
  resblock_updown: True
  # The type of resnet block to use
  resnet_block_type: 'biggan'
  # Dropout scale
  dropout: 0.1
  # Is this a v or epsilon-param model?
  is_v_param: True
  # True if this is a class conditional model
  is_class_conditional: True

data:
  # Spatial width/height of the data. For MNIST, we resize
  # to 32 to make the math easier.
  image_size: 32
  # Number of channels in the input data
  num_channels: 1
  # The number of classes in the dataset
  num_classes: 10
